Repository cnumr/ecoCode, pull requests merged in 2022-11, with the labels that each got.

#168 add rule: avoid multiple if else statement
  src/java-plugin/src/main/java/fr/cnumr/java/RulesList.java
  src/java-plugin/src/main/java/fr/cnumr/java/checks/AvoidMultipleIfElseStatement.java
  src/java-plugin/src/main/resources/fr/cnumr/l10n/java/rules/java/AMIES.html
  src/java-plugin/src/main/resources/fr/cnumr/l10n/java/rules/java/AMIES.json
  src/java-plugin/src/test/files/AvoidMultipleIfElseStatement.java
  src/java-plugin/src/test/files/AvoidMultipleIfElseStatementNoIssue.java
  src/java-plugin/src/test/java/fr/cnumr/java/MyJavaFileCheckRegistrarTest.java
  src/java-plugin/src/test/java/fr/cnumr/java/checks/AvoidMultipleIfElseStatementTest.java
Labels: plugin:java, rule

#141 Fix some Sonar Bugs and code smell
  .gitignore
  README.md
  src/.gitignore
  src/android-plugin/src/main/java/io/ecocode/java/checks/batch/JobCoalesceRule.java
  src/android-plugin/src/main/java/io/ecocode/java/checks/batch/SensorCoalesceRule.java
  src/android-plugin/src/main/java/io/ecocode/java/checks/bottleneck/UncompressedDataTransmissionRule.java
  src/android-plugin/src/main/java/io/ecocode/java/checks/helpers/CheckArgumentComplexTypeUtils.java
  src/android-plugin/src/main/java/io/ecocode/java/checks/helpers/ConstructorBeforeMethodCheck.java
  src/android-plugin/src/main/java/io/ecocode/java/checks/helpers/TreeHelper.java
  src/android-plugin/src/main/java/io/ecocode/java/checks/helpers/constant/ArgumentValueOnMethodCheck.java
  src/android-plugin/src/main/java/io/ecocode/java/checks/idleness/KeepVoiceAwakeRule.java
  src/android-plugin/src/main/java/io/ecocode/java/checks/power/ChargeAwarenessRule.java
  src/android-plugin/src/main/java/io/ecocode/java/checks/power/SaveModeAwarenessRule.java
  src/android-plugin/src/main/java/io/ecocode/java/checks/sobriety/HighFrameRateRule.java
  src/android-plugin/src/main/java/io/ecocode/java/checks/sobriety/ThriftyGeolocationCriteriaRule.java
  src/android-plugin/src/main/java/io/ecocode/java/checks/sobriety/ThriftyGeolocationMinDistanceRule.java
  src/android-plugin/src/main/java/io/ecocode/java/checks/sobriety/ThriftyGeolocationMinTimeRule.java
  src/android-plugin/src/main/java/io/ecocode/java/checks/sobriety/VibrationFreeRule.java
  src/android-plugin/src/main/java/io/ecocode/xml/checks/helpers/CheckPermissionsRule.java
  src/android-plugin/src/main/java/io/ecocode/xml/checks/power/ChargeAwarenessXmlRule.java
  src/android-plugin/src/test/java/io/ecocode/java/JavaEcoCodeProfileTest.java
  src/android-plugin/src/test/java/io/ecocode/xml/XmlEcoCodeProfileTest.java
  src/java-plugin/src/main/java/fr/cnumr/java/checks/AvoidSQLRequestInLoop.java
  src/java-plugin/src/main/java/fr/cnumr/java/checks/IncrementCheck.java
  src/java-plugin/src/main/java/fr/cnumr/java/checks/NoFunctionCallWhenDeclaringForLoop.java
  src/java-plugin/src/main/java/fr/cnumr/java/checks/UnnecessarilyAssignValuesToVariables.java
  src/java-plugin/src/test/java/fr/cnumr/java/MyJavaRulesDefinitionTest.java
  src/java-plugin/src/test/java/fr/cnumr/java/checks/AvoidSpringRepositoryCallInLoopCheckTest.java
  src/java-plugin/src/test/java/fr/cnumr/java/checks/NoFunctionCallWhenDeclaringForLoopTest.java
  src/php-plugin/src/main/java/fr/cnumr/php/checks/AvoidDoubleQuoteCheck.java
  src/php-plugin/src/main/java/fr/cnumr/php/checks/AvoidFullSQLRequestCheck.java
  src/php-plugin/src/main/java/fr/cnumr/php/checks/AvoidSQLRequestInLoopCheck.java
  src/php-plugin/src/main/java/fr/cnumr/php/checks/NoFunctionCallWhenDeclaringForLoop.java
  src/python-plugin/src/main/java/fr/cnumr/python/checks/AvoidFullSQLRequest.java
  src/python-plugin/src/main/java/fr/cnumr/python/checks/AvoidGlobalVariableInFunctionCheck.java
  src/python-plugin/src/main/java/fr/cnumr/python/checks/AvoidTryCatchFinallyCheck.java
  src/python-plugin/src/main/java/fr/cnumr/python/checks/NoFunctionCallWhenDeclaringForLoop.java
Labels: bug, refactoring

#175 Correction of command maven warnings and refactoring jdk version usage
  src/android-plugin/pom.xml
  src/java-plugin/pom.xml
  src/php-plugin/pom.xml
  src/pom.xml
  src/python-plugin/pom.xml
  src/xml-plugin/pom.xml
Labels: bug, refactoring

#181 Rename tool scripts and add add new one
  src/0_init_reinit.sh
  src/1_compile.sh
  src/2_build.sh
  src/3_start.sh
  src/4_stop.sh
Labels: enhancement, refactoring
